### ISSUE TITLE
padding option should be explicitly specified

### ISSUE THREAD

**Issue by yuhanliu0121** [AntonSemechko/exact_histogram#1]
Very great work but there might be a minor error at line 53 of pixel_order.m, which is 
>FR_j=imfilter(double(im(:,:,1)),F{j})

it is supposed to be 
>FR_j=imfilter(double(im(:,:,1)),F{j}, 'replicate')

because in the reference paper on exact histogram specification you mentioned "We assume that the image is expanded by replicating the border pixels in order to accommodate W_k on its borders" in the fourth paragraph of section three.

I am using R2020b. The default padding mechanism is to assign 0 to values outside the bounds. I am not sure if it is the same case when you released the code.

**Comment by AntonSemechko** [comment]
Hi! Thank you for reporting that bug. It has now been fixed. 

Cheers!
